"""add image and bio to pets

Revision ID: f5cc0c81d3ed
Revises: 381593a0ac65
Create Date: 2026-01-18 23:30:41.198074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5cc0c81d3ed'
down_revision = '381593a0ac65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
